image: python

variables:
  TWINE_USERNAME: SECURE
  TWINE_PASSWORD: SECURE
  TWINE_REPOSITORY_URL: https://upload.pypi.org/legacy/

before_script:
  - curl -O https://bootstrap.pypa.io/get-pip.py
  - python get-pip.py
  - pip install -r requirements_dev.txt

after_script:
  - pip install codecov
  - make install-dev
  - detect_software_versions python -p build -o software_versions.md
  # - codecov --token=<>

stages:
  - quick-checks
  - build
  - test
  - validation
  - deploy
  - report
  - cleanup

linters:
  image: python:3.5
  stage: quick-checks
  script:
    - make lint
    # - tox -e linters

build:
  stage: build
  script:
    - make install-dev
    - make dist
  artifacts:
    paths:
    - dist/
    - software_versions.md
    expire_in: 1 month

failed:build:
  stage: build
  script:
    - exit 1
  allow_failure: true
  artifacts:
    paths:
      - software_versions.md
    when: always
    expire_in: 1 month

.test: &test_setup
  stage: test
  artifacts:
    paths:
      - software_versions.md
    when: always
    expire_in: 1 month

python2:
  <<: *test_setup
  image: python:2.7
  script: tox -e py27

python36:
  <<: *test_setup
  image: python:3.6
  script: tox -e py36

python37:
  <<: *test_setup
  image: python:3.7
  script: tox -e py37

docs:
  <<: *test_setup
  script: make docs


validate-root-diff:
  image: python:3.7
  stage: validation
  script:
    - make install
    - mkdir -p output/validate/test_1_2
    - mkdir -p output/validate/test_1_3
    - skvalidate root_diff tests/samples/test_1.root tests/samples/test_2.root --out-dir=output/validate/test_1_2
    - skvalidate root_diff tests/samples/test_1.root tests/samples/test_3.root --out-dir=output/validate/test_1_3
  artifacts:
    paths:
      - output/validate
      - software_versions.md
    expire_in: 1 week

validate:demo_report:
  image: python:3.7
  stage: validation
  script:
    - make install
    - make_demo_report
    - test -f demo_report.md
  artifacts:
    paths:
      - demo_report.md
      - software_versions.md
    expire_in: 1 week

validate:metric_pipeline:
  image: python:3.7
  stage: validation
  script:
    - make install-dev
    - apt update && apt install stress
    - ./.ci/test_metric_pipeline.sh
    - make_demo_report
    - test -f demo_report.md
  artifacts:
    paths:
      - demo_report.md
      - skvalidate/data/examples/*.json
      - software_versions.md
    expire_in: 1 week

failed:validation:
  stage: validation
  script:
    - exit 1
  allow_failure: true
  artifacts:
    paths:
      - software_versions.md
    when: always
    expire_in: 1 month

deploy_pypi:
  stage: deploy
  script:
    - pip install -U twine setuptools
    - python setup.py check sdist bdist_wheel
    - twine upload dist/*
  only:
    - tags
  except:
    - branches

report:
  stage: report
  when: always
  script:
    - make install
    - make_report .ci/ci_report.yml -o ci_report.md
  dependencies:
    - validate-root-diff
    - validate:metric_pipeline
  artifacts:
    paths:
      - ci_report.md
    expire_in: 1 week

cleanup_pypirc:
   stage: cleanup
   when: always   # this is important; run even if preceding stages failed.
   script:
    - rm -vf ~/.pypirc  # we don't want to leave these around, but GitLab may clean up anyway.
