image: python

variables:
  TWINE_USERNAME: SECURE
  TWINE_PASSWORD: SECURE
  TWINE_REPOSITORY_URL: https://upload.pypi.org/legacy/

before_script:
  - curl -O https://bootstrap.pypa.io/get-pip.py
  - python get-pip.py
  - pip install -r requirements_dev.txt

after_script:
  - pip install codecov
  # - codecov --token=<>

stages:
  - quick-checks
  - build
  - test
  - validation
  - deploy
  - cleanup

linters:
  image: python:3.5
  stage: quick-checks
  script:
    - make lint
    # - tox -e linters

build:
  stage: build
  script:
    - make install-dev
    - make dist
  artifacts:
    paths:
    - dist/
    expire_in: 1 month

python2:
  image: python:2.7
  stage: test
  script: tox -e py27

python36:
  image: python:3.6
  stage: test
  script: tox -e py36

python37:
  image: python:3.7
  stage: test
  script: tox -e py37

docs:
  stage: test
  script: make docs


validate-root-diff:
  image: python:3.7
  stage: validation
  script:
    - make install
    - mkdir -p output/validate/test_1_2 output/validate/test_1_3
    - skvalidate root_diff tests/samples/test_1.root tests/samples/test_2.root --out-dir=output/validate/test_1_2
    - skvalidate root_diff tests/samples/test_1.root tests/samples/test_3.root --out-dir=output/validate/test_1_3
  artifacts:
    paths:
    - output/validate
    expire_in: 1 week


deploy_pypi:
  stage: deploy
  script:
    - pip install -U twine setuptools
    - python setup.py check sdist bdist_wheel
    - twine upload dist/*
  only:
    - tags
  except:
    - branches


cleanup_pypirc:
   stage: cleanup
   when: always   # this is important; run even if preceding stages failed.
   script:
    - rm -vf ~/.pypirc  # we don't want to leave these around, but GitLab may clean up anyway.
