
output_file: demo_report.md
template: {{scikit_validate}}/templates/report/default/summary.md
output_url:
  function: skvalidate.report.demo.get_output_url
pipeline_url:
  function: skvalidate.report.demo.get_pipeline_url
title: "scikit-validate DEMO report"

sections:
  software_report:
    template: {{scikit_validate}}/templates/report/default/software.md
    versions:
      function: skvalidate.report.demo.software_versions

  build_report:
    template: {{scikit_validate}}/templates/report/default/build.md
    builds:
      function: skvalidate.report.demo.get_jobs_for_stage
      stage: build
      symbol_ok: '&#9989;'
      symbol_fail: '&#10060;'

  test_report:
    template: {{scikit_validate}}/templates/report/default/test.md
    tests:
      function: skvalidate.report.demo.get_jobs_for_stage
      stage: test
      symbol_ok: '&#9989;'
      symbol_fail: '&#10060;'

  validation_report:
    template: {{scikit_validate}}/templates/report/default/validation.md
    validation:
      function: skvalidate.report.demo.get_jobs_for_stage
      stage: validation
      symbol_ok: '&#9989;'
      symbol_differ: '&#10060;'
      symbol_unkown: '&#10067;'


  performance_report:
    template: {{scikit_validate}}/templates/report/default/performance.md
    metrics:
      function: skvalidate.report.demo.get_metrics
      metrics_json: performance_metrics.json
      symbol_up: '&#10138;'
      symbol_down: '&#10136;'
      symbol_same: '&#10134;'

  file_report:
    template: {{scikit_validate}}/templates/report/default/file_metrics.md
    file_metrics:
      function: skvalidate.report.demo.get_metrics
      metrics_json: file_metrics.json
      symbol_up: '&#10138;'
      symbol_down: '&#10136;'
      symbol_same: '&#10134;'
