
general:
  output_file: demo_report.md
  template: {{scikit_validate}}/templates/report/default/summary.md
  output_url:
    function: skvalidate.dummy.get_output_url
  pipeline_url:
    function: skvalidate.dummy.get_pipeline_url
  title: "scikit-validate DEMO report"

sections:
  software_report:
    template: {{scikit_validate}}/templates/default/report/software.md
    versions: skvalidate.dummy.software_versions

  build_report:
    template: {{scikit_validate}}/templates/default/report/builds.md
    builds:
      function: skvalidate.dummy.get_jobs_for_stage
      stage: build

  test_report:
    template: {{scikit_validate}}/templates/default/report/test.md
    builds:
      function: skvalidate.dummy.get_jobs_for_stage
      stage: test

  validation_report:
    template: {{scikit_validate}}/templates/default/report/validation.md
    validation:
      function: skvalidate.dummy.get_jobs_for_stage
      stage: validation
      image_ok: {{scikit_validate}}/data/images/ok.png
      image_differ: {{scikit_validate}}/data/images/differ.png
      image_unkown: {{scikit_validate}}/data/images/unkown.png


  performance_report:
    template: {{scikit_validate}}/templates/default/report/performance.md
    metrics:
      function: skvalidate.dummy.get_metrics
      metrics_json: metrics.json

  file_report:
    template: {{scikit_validate}}/templates/default/report/performance.md
    file_metrics:
      function: skvalidate.dummy.get_metrics
      metrics_json: metrics.json
